modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="olmod"
version="0.1.0"
displayName="Ol Mod"
description='''/ol komutuyla oyuncu/köpek/kedi/at rolleri arasında geçiş yapan mod.'''

[[dependencies.olmod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.olmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
